[project]
name = "braincare"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "bleak>=1.1.1",
    "nest-asyncio>=1.6.0",
    "numpy>=2.2.6",
    "pyqt5>=5.15.11",
    "pyqtgraph>=0.13.7",
]
